### ISSUE TITLE
A bug in the mail triggering module.

### ISSUE THREAD

**Issue by sudb97** [sudb97/Amazon-Tracking#1]
Mail is not getting triggered as per requirement.

**Comment by ParnaSankarPan** [comment]
I would like work on the above issue and contribute my solution to the problem .Please provide me with the necessary requirements so that I will start working on it. Since it is mandatory for my course requirement I assure you for the completion of the issue.

**Comment by sudb97** [comment]
please go through the provided documentations that will help you to proceed with the work.
https://developers.google.com/gmail/api/guides/sending#python
https://tools.ietf.org/html/rfc2822#appendix-A.2
https://developers.google.com/identity/protocols/oauth2

Create API token before using google APIs.
Let me know in case of any difficulties.
